name: jackshub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  cupertino_icons: ^0.1.2
  fluro: "^1.4.0"
  auto_size_text: ^2.1.0
  intl: ^0.16.0
  sqflite:
  path_provider:
  flutter_bloc:
  equatable:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true
  fonts:
    - family: Hobo
      fonts:
        - asset: assets/fonts/HoboBT.ttf
  assets:
    - assets/images/
